on:
  push:
    branches:
      - main
      - master

name: release

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: ruby
          package-name: dishwasher
