name: StandardRB

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  lint:
    name: StandardRB Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.267.0
        with:
          bundler-cache: true
      - name: Run StandardRB
        run: bundle exec standardrb --format progress
