name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.3', '3.2', '3.1']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
