name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    name: RSpec Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.267.0
        with:
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
